name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror repository to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git config --global user.email "bcpc07laichau@gmail.com"
          git config --global user.name "bcpc07laichau"
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/pc071/pccc.git
          git push gitlab main --force
          git push --tags gitlab --force
